#!/usr/bin/env python3.10
from locations.ip_location import IPLocator
from services.openweather_service import OpenWeatherService
from config.settings import IP_URL

def main():
    location = IPLocator(IP_URL)
    weather_service = OpenWeatherService(location.get_coordinates())

    print(weather_service.get_weather())


if __name__ == "__main__":
    main()
